//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPractice_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fuel()
        {
            this.remains = new HashSet<remains>();
        }
    
        public int fuel_id { get; set; }
        public string fuel_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public int sup_id { get; set; }
    
        public virtual supplierdir supplierdir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<remains> remains { get; set; }
    }
}
