//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPractice_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_GasStationEntities : DbContext
    {
        public static BD_GasStationEntities _context;
        public BD_GasStationEntities()
            : base("name=BD_GasStationEntities")
        {
        }
        public static BD_GasStationEntities GetContext()
        {
            if(_context == null)
            {
                _context = new BD_GasStationEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fuel> fuel { get; set; }
        public virtual DbSet<remains> remains { get; set; }
        public virtual DbSet<supplierdir> supplierdir { get; set; }
    }
}
