//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPractice_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remains
    {
        public int remain_id { get; set; }
        public int fuel_id { get; set; }
        public Nullable<System.DateTime> remain_date { get; set; }
        public Nullable<decimal> vol_init { get; set; }
        public Nullable<decimal> vol_sold { get; set; }
    
        public virtual fuel fuel { get; set; }
    }
}
